                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              -- ========================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              -- MIGRACIÓN: Sistema de 3 planes con efecto anclaje
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              -- Emprendedor / Profesional / (Taller+ visual)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              --
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              -- Estrategia: NO se agregan nuevos valores al ENUM plan_type.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              -- Se quita el constraint UNIQUE de plans.tipo y se crean múltiples
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              -- rows con tipo='PREMIUM' diferenciadas por slug.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              -- Los 25+ lugares que chequean planTipo === 'PREMIUM' siguen funcionando.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              -- ========================================

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              -- 1. Quitar constraint UNIQUE de tipo (permite múltiples planes PREMIUM)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ALTER TABLE plans DROP CONSTRAINT IF EXISTS plans_tipo_key;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              -- 2. Agregar columnas nuevas
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ALTER TABLE plans ADD COLUMN IF NOT EXISTS slug TEXT;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ALTER TABLE plans ADD COLUMN IF NOT EXISTS tier_order INTEGER DEFAULT 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ALTER TABLE plans ADD COLUMN IF NOT EXISTS feature_flags JSONB DEFAULT '{}'::jsonb;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              -- 3. Actualizar plan FREE existente con su slug
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              UPDATE plans
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              SET
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                slug = 'free',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                tier_order = 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                feature_flags = '{}'::jsonb
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              WHERE tipo = 'FREE';

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              -- 4. Actualizar plan PREMIUM existente → ahora es "Profesional"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              UPDATE plans
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              SET
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                slug = 'profesional',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                tier_order = 2,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                nombre = 'Profesional',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                descripcion = 'Todo lo que tu taller necesita',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                feature_flags = jsonb_build_object(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  'advanced_reports', true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  'whatsapp_notifications', true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  'kiosk_mode', true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  'pos_sales', true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  'client_portal', true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  'data_export', true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  'custom_logo', true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  'cuenta_corriente', true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  'cotizaciones_online', true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  'gestion_proveedores', true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  'import_export', true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  'firma_digital', true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  'fotos_etapa', true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  'garantias', true
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              WHERE tipo = 'PREMIUM' AND slug IS NULL;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              -- 5. Agregar UNIQUE constraint a slug (después de backfill)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ALTER TABLE plans ADD CONSTRAINT plans_slug_key UNIQUE (slug);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              -- 6. Insertar plan Emprendedor (tipo=PREMIUM para que isPremium siga funcionando)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              INSERT INTO plans (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                nombre,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                tipo,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                slug,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                tier_order,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                descripcion,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                precio_mensual,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                precio_anual,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                precio_mensual_usd,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                precio_anual_usd,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                moneda,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                limite_ordenes,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                limite_tecnicos,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                limite_clientes,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                limite_vendedores,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                limite_storage_mb,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                feature_flags,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                features,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                activo
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              VALUES (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                generate_cuid(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'Emprendedor',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'PREMIUM',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'emprendedor',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'Para talleres que recién arrancan',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                10999,  -- ~55% de Profesional (19999)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                105590, -- ~55% de Profesional anual (191990)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                8,      -- USD mensual
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                77,     -- USD anual
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'ARS',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                30,     -- Hasta 30 órdenes/mes
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                1,      -- 1 técnico
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                NULL,   -- Clientes ilimitados
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                2,      -- 2 vendedores
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                1000,   -- 1GB storage
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                jsonb_build_object(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  'pos_sales', true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  'fotos_etapa', true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  'garantias', true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  'firma_digital', true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  'cuenta_corriente', true
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                '["Hasta 30 órdenes/mes","1 técnico","2 vendedores","Clientes ilimitados","1GB almacenamiento","Soporte por email","Punto de venta","Firma digital","Garantías","Cuenta corriente"]'::jsonb,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                TRUE
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ON CONFLICT (slug) DO NOTHING;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              -- 7. Actualizar función de creación de suscripción para seleccionar por slug
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              CREATE OR REPLACE FUNCTION create_free_subscription(org_id TEXT)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              RETURNS TEXT AS $$
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              DECLARE
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                target_plan_id TEXT;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                new_sub_id TEXT;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              BEGIN
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                -- Trial se crea siempre con el plan Profesional (acceso total)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                SELECT id INTO target_plan_id
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                FROM plans
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                WHERE slug = 'profesional' AND activo = TRUE
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                LIMIT 1;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                -- Fallback: cualquier plan PREMIUM activo si no hay slug
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                IF target_plan_id IS NULL THEN
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  SELECT id INTO target_plan_id
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  FROM plans
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  WHERE tipo = 'PREMIUM' AND activo = TRUE
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ORDER BY tier_order DESC NULLS LAST
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  LIMIT 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                END IF;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                IF target_plan_id IS NULL THEN
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  RAISE EXCEPTION 'No plan found for trial subscription';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                END IF;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                -- Crear suscripción con trial de 30 días
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                INSERT INTO subscriptions (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  organization_id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  plan_id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  status,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  current_period_start,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  current_period_end,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  trial_end
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                VALUES (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  org_id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  target_plan_id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  'TRIALING',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  NOW(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  NOW() + INTERVAL '30 days',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  NOW() + INTERVAL '30 days'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                RETURNING id INTO new_sub_id;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                -- Crear registro de uso
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                INSERT INTO organization_usage (organization_id)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                VALUES (org_id)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ON CONFLICT (organization_id) DO NOTHING;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                RETURN new_sub_id;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              END;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              $$ LANGUAGE plpgsql;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              -- 8. Índice para búsquedas por slug (alta frecuencia)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              CREATE INDEX IF NOT EXISTS plans_slug_idx ON plans(slug) WHERE activo = TRUE;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              CREATE INDEX IF NOT EXISTS plans_tier_order_idx ON plans(tier_order DESC) WHERE activo = TRUE;
